name: First Showcase Workflow

on:
  push:
    branches: 
      - main
  workflow_dispatch:
  
jobs:
  FirstJob:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "Hello world from first job!"

      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: List files in repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
